In [2]:
import pandas as pd

In [3]:
nba = pd.read_csv("nba.csv") #a callection of all NBA players
                       #NaN is pandas designation for empty values
                       #shows first 30 rows and last 30 rows
                       #pandas converts all integers to floating point (age is not floating point originally in the .CSV)

## Shared Methods and Attributes

In [4]:
nba.head(4) #first 4 rows of the dataframe

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0

In [5]:
nba.tail() #last 5 rows of the dataframe

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
nba.index #object representing what stores the indexes of the datafame

RangeIndex(start=0, stop=458, step=1)

In [7]:
nba.values #each row is a list in a nested list

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [8]:
nba.shape  #how many rows and columns

(458, 9)

In [9]:
nba.dtypes   #gives datatype of every single column of the dataframe

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [10]:
nba.columns  #gives the name of columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [11]:
nba.axes   #bundles column names and index rage

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [12]:
nba.info()  #we see there are some college and salary values missing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [13]:
nba.get_dtype_counts()   #datatypes and how many columns have that datatype

float64    4
object     5
dtype: int64

## Differences between Shared Methods

In [17]:
rev = pd.read_csv("revenue.csv", index_col = "Date")

In [18]:
rev.head(3)

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933

In [19]:
s = pd.Series([1, 2, 3])
s.sum()

6

In [20]:
s

0    1
1    2
2    3
dtype: int64

In [21]:
rev.sum() #we get a new dataframe with column names as indexes and sum of values as indexes

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [22]:
rev.sum(axis="index") #axes equals 0

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [23]:
rev.sum(axis="columns") #axes equals 1

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

## Select One Column from DataFrame

In [25]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [26]:
nba.Name #extracts the Name column -> panda extracts it as a series

0                Avery Bradley
1                  Jae Crowder
2                 John Holland
3                  R.J. Hunter
4                Jonas Jerebko
5                 Amir Johnson
6                Jordan Mickey
7                 Kelly Olynyk
8                 Terry Rozier
9                 Marcus Smart
10             Jared Sullinger
11               Isaiah Thomas
12                 Evan Turner
13                 James Young
14                Tyler Zeller
15            Bojan Bogdanovic
16                Markel Brown
17             Wayne Ellington
18     Rondae Hollis-Jefferson
19                Jarrett Jack
20              Sergey Karasev
21             Sean Kilpatrick
22                Shane Larkin
23                 Brook Lopez
24            Chris McCullough
25                 Willie Reed
26             Thomas Robinson
27                  Henry Sims
28                Donald Sloan
29              Thaddeus Young
                ...
428            Al-Farouq Aminu
429            Pat Connaughton
430               Allen Crabbe
431                   Ed Davis
432           Maurice Harkless
433           Gerald Henderson
434                Chris Kaman
435             Meyers Leonard
436             Damian Lillard
437              C.J. McCollum
438               Luis Montero
439              Mason Plumlee
440              Brian Roberts
441                Noah Vonleh
442              Trevor Booker
443                 Trey Burke
444                 Alec Burks
445                 Dante Exum
446             Derrick Favors
447                Rudy Gobert
448             Gordon Hayward
449                Rodney Hood
450                 Joe Ingles
451              Chris Johnson
452                 Trey Lyles
453               Shelvin Mack
454                  Raul Neto
455               Tibor Pleiss
456                Jeff Withey
457                        NaN
Name: Name, Length: 458, dtype: object

In [27]:
nba.Number

0       0.0
1      99.0
2      30.0
3      28.0
4       8.0
5      90.0
6      55.0
7      41.0
8      12.0
9      36.0
10      7.0
11      4.0
12     11.0
13     13.0
14     44.0
15     44.0
16     22.0
17     21.0
18     24.0
19      2.0
20     10.0
21      6.0
22      0.0
23     11.0
24      1.0
25     33.0
26     41.0
27     14.0
28     15.0
29     30.0
       ...
428     8.0
429     5.0
430    23.0
431    17.0
432     4.0
433     9.0
434    35.0
435    11.0
436     0.0
437     3.0
438    44.0
439    24.0
440     2.0
441    21.0
442    33.0
443     3.0
444    10.0
445    11.0
446    15.0
447    27.0
448    20.0
449     5.0
450     2.0
451    23.0
452    41.0
453     8.0
454    25.0
455    21.0
456    24.0
457     NaN
Name: Number, Length: 458, dtype: float64

In [28]:
nba.Salary

0       7730337.0
1       6796117.0
2             NaN
3       1148640.0
4       5000000.0
5      12000000.0
6       1170960.0
7       2165160.0
8       1824360.0
9       3431040.0
10      2569260.0
11      6912869.0
12      3425510.0
13      1749840.0
14      2616975.0
15      3425510.0
16       845059.0
17      1500000.0
18      1335480.0
19      6300000.0
20      1599840.0
21       134215.0
22      1500000.0
23     19689000.0
24      1140240.0
25       947276.0
26       981348.0
27       947276.0
28       947276.0
29     11235955.0
          ...
428     8042895.0
429      625093.0
430      947276.0
431     6980802.0
432     2894059.0
433     6000000.0
434     5016000.0
435     3075880.0
436     4236287.0
437     2525160.0
438      525093.0
439     1415520.0
440     2854940.0
441     2637720.0
442     4775000.0
443     2658240.0
444     9463484.0
445     3777720.0
446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [30]:
nba["Salary"]   #extract Salary using square brackets 
                #this also works when the column name has a space

0       7730337.0
1       6796117.0
2             NaN
3       1148640.0
4       5000000.0
5      12000000.0
6       1170960.0
7       2165160.0
8       1824360.0
9       3431040.0
10      2569260.0
11      6912869.0
12      3425510.0
13      1749840.0
14      2616975.0
15      3425510.0
16       845059.0
17      1500000.0
18      1335480.0
19      6300000.0
20      1599840.0
21       134215.0
22      1500000.0
23     19689000.0
24      1140240.0
25       947276.0
26       981348.0
27       947276.0
28       947276.0
29     11235955.0
          ...
428     8042895.0
429      625093.0
430      947276.0
431     6980802.0
432     2894059.0
433     6000000.0
434     5016000.0
435     3075880.0
436     4236287.0
437     2525160.0
438      525093.0
439     1415520.0
440     2854940.0
441     2637720.0
442     4775000.0
443     2658240.0
444     9463484.0
445     3777720.0
446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [31]:
type(nba["Name"])

pandas.core.series.Series

## Select Two or More Columns from a DataFrame

In [32]:
nba[["Team", "Name"]]   # we get a new dataframe

                       Team                     Name
0            Boston Celtics            Avery Bradley
1            Boston Celtics              Jae Crowder
2            Boston Celtics             John Holland
3            Boston Celtics              R.J. Hunter
4            Boston Celtics            Jonas Jerebko
5            Boston Celtics             Amir Johnson
6            Boston Celtics            Jordan Mickey
7            Boston Celtics             Kelly Olynyk
8            Boston Celtics             Terry Rozier
9            Boston Celtics             Marcus Smart
10           Boston Celtics          Jared Sullinger
11           Boston Celtics            Isaiah Thomas
12           Boston Celtics              Evan Turner
13           Boston Celtics              James Young
14           Boston Celtics             Tyler Zeller
15            Brooklyn Nets         Bojan Bogdanovic
16            Brooklyn Nets             Markel Brown
17            Brooklyn Nets          Wayne Ellington
18            Brooklyn Nets  Rondae Hollis-Jefferson
19            Brooklyn Nets             Jarrett Jack
20            Brooklyn Nets           Sergey Karasev
21            Brooklyn Nets          Sean Kilpatrick
22            Brooklyn Nets             Shane Larkin
23            Brooklyn Nets              Brook Lopez
24            Brooklyn Nets         Chris McCullough
25            Brooklyn Nets              Willie Reed
26            Brooklyn Nets          Thomas Robinson
27            Brooklyn Nets               Henry Sims
28            Brooklyn Nets             Donald Sloan
29            Brooklyn Nets           Thaddeus Young
..                      ...                      ...
428  Portland Trail Blazers          Al-Farouq Aminu
429  Portland Trail Blazers          Pat Connaughton
430  Portland Trail Blazers             Allen Crabbe
431  Portland Trail Blazers                 Ed Davis
432  Portland Trail Blazers         Maurice Harkless
433  Portland Trail Blazers         Gerald Henderson
434  Portland Trail Blazers              Chris Kaman
435  Portland Trail Blazers           Meyers Leonard
436  Portland Trail Blazers           Damian Lillard
437  Portland Trail Blazers            C.J. McCollum
438  Portland Trail Blazers             Luis Montero
439  Portland Trail Blazers            Mason Plumlee
440  Portland Trail Blazers            Brian Roberts
441  Portland Trail Blazers              Noah Vonleh
442               Utah Jazz            Trevor Booker
443               Utah Jazz               Trey Burke
444               Utah Jazz               Alec Burks
445               Utah Jazz               Dante Exum
446               Utah Jazz           Derrick Favors
447               Utah Jazz              Rudy Gobert
448               Utah Jazz           Gordon Hayward
449               Utah Jazz              Rodney Hood
450               Utah Jazz               Joe Ingles
451               Utah Jazz            Chris Johnson
452               Utah Jazz               Trey Lyles
453               Utah Jazz             Shelvin Mack
454               Utah Jazz                Raul Neto
455               Utah Jazz             Tibor Pleiss
456               Utah Jazz              Jeff Withey
457                     NaN                      NaN

[458 rows x 2 columns]

In [33]:
nba[["Number", "College"]]

     Number            College
0       0.0              Texas
1      99.0          Marquette
2      30.0  Boston University
3      28.0      Georgia State
4       8.0                NaN
5      90.0                NaN
6      55.0                LSU
7      41.0            Gonzaga
8      12.0         Louisville
9      36.0     Oklahoma State
10      7.0         Ohio State
11      4.0         Washington
12     11.0         Ohio State
13     13.0           Kentucky
14     44.0     North Carolina
15     44.0                NaN
16     22.0     Oklahoma State
17     21.0     North Carolina
18     24.0            Arizona
19      2.0       Georgia Tech
20     10.0                NaN
21      6.0         Cincinnati
22      0.0         Miami (FL)
23     11.0           Stanford
24      1.0           Syracuse
25     33.0        Saint Louis
26     41.0             Kansas
27     14.0         Georgetown
28     15.0          Texas A&M
29     30.0       Georgia Tech
..      ...                ...
428     8.0        Wake Forest
429     5.0         Notre Dame
430    23.0         California
431    17.0     North Carolina
432     4.0         St. John's
433     9.0               Duke
434    35.0   Central Michigan
435    11.0           Illinois
436     0.0        Weber State
437     3.0             Lehigh
438    44.0     Westchester CC
439    24.0               Duke
440     2.0             Dayton
441    21.0            Indiana
442    33.0            Clemson
443     3.0           Michigan
444    10.0           Colorado
445    11.0                NaN
446    15.0       Georgia Tech
447    27.0                NaN
448    20.0             Butler
449     5.0               Duke
450     2.0                NaN
451    23.0             Dayton
452    41.0           Kentucky
453     8.0             Butler
454    25.0                NaN
455    21.0                NaN
456    24.0             Kansas
457     NaN                NaN

[458 rows x 2 columns]

In [34]:
select = ["Salary", "Team", "Name"]

In [35]:
nba[select] #cleaner syntax using a list to select columns

         Salary                    Team                     Name
0     7730337.0          Boston Celtics            Avery Bradley
1     6796117.0          Boston Celtics              Jae Crowder
2           NaN          Boston Celtics             John Holland
3     1148640.0          Boston Celtics              R.J. Hunter
4     5000000.0          Boston Celtics            Jonas Jerebko
5    12000000.0          Boston Celtics             Amir Johnson
6     1170960.0          Boston Celtics            Jordan Mickey
7     2165160.0          Boston Celtics             Kelly Olynyk
8     1824360.0          Boston Celtics             Terry Rozier
9     3431040.0          Boston Celtics             Marcus Smart
10    2569260.0          Boston Celtics          Jared Sullinger
11    6912869.0          Boston Celtics            Isaiah Thomas
12    3425510.0          Boston Celtics              Evan Turner
13    1749840.0          Boston Celtics              James Young
14    2616975.0          Boston Celtics             Tyler Zeller
15    3425510.0           Brooklyn Nets         Bojan Bogdanovic
16     845059.0           Brooklyn Nets             Markel Brown
17    1500000.0           Brooklyn Nets          Wayne Ellington
18    1335480.0           Brooklyn Nets  Rondae Hollis-Jefferson
19    6300000.0           Brooklyn Nets             Jarrett Jack
20    1599840.0           Brooklyn Nets           Sergey Karasev
21     134215.0           Brooklyn Nets          Sean Kilpatrick
22    1500000.0           Brooklyn Nets             Shane Larkin
23   19689000.0           Brooklyn Nets              Brook Lopez
24    1140240.0           Brooklyn Nets         Chris McCullough
25     947276.0           Brooklyn Nets              Willie Reed
26     981348.0           Brooklyn Nets          Thomas Robinson
27     947276.0           Brooklyn Nets               Henry Sims
28     947276.0           Brooklyn Nets             Donald Sloan
29   11235955.0           Brooklyn Nets           Thaddeus Young
..          ...                     ...                      ...
428   8042895.0  Portland Trail Blazers          Al-Farouq Aminu
429    625093.0  Portland Trail Blazers          Pat Connaughton
430    947276.0  Portland Trail Blazers             Allen Crabbe
431   6980802.0  Portland Trail Blazers                 Ed Davis
432   2894059.0  Portland Trail Blazers         Maurice Harkless
433   6000000.0  Portland Trail Blazers         Gerald Henderson
434   5016000.0  Portland Trail Blazers              Chris Kaman
435   3075880.0  Portland Trail Blazers           Meyers Leonard
436   4236287.0  Portland Trail Blazers           Damian Lillard
437   2525160.0  Portland Trail Blazers            C.J. McCollum
438    525093.0  Portland Trail Blazers             Luis Montero
439   1415520.0  Portland Trail Blazers            Mason Plumlee
440   2854940.0  Portland Trail Blazers            Brian Roberts
441   2637720.0  Portland Trail Blazers              Noah Vonleh
442   4775000.0               Utah Jazz            Trevor Booker
443   2658240.0               Utah Jazz               Trey Burke
444   9463484.0               Utah Jazz               Alec Burks
445   3777720.0               Utah Jazz               Dante Exum
446  12000000.0               Utah Jazz           Derrick Favors
447   1175880.0               Utah Jazz              Rudy Gobert
448  15409570.0               Utah Jazz           Gordon Hayward
449   1348440.0               Utah Jazz              Rodney Hood
450   2050000.0               Utah Jazz               Joe Ingles
451    981348.0               Utah Jazz            Chris Johnson
452   2239800.0               Utah Jazz               Trey Lyles
453   2433333.0               Utah Jazz             Shelvin Mack
454    900000.0               Utah Jazz                Raul Neto
455   2900000.0               Utah Jazz             Tibor Pleiss
456    947276.0               Utah Jazz              Jeff Withey
457         NaN                     NaN                      NaN

[458 rows x 3 columns]

## Add New Column to DataFrame

In [36]:
nba["Sport"] = "Basketball"  #every value in the new Sport column will be Basketball

In [37]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,Basketball
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,Basketball
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,Basketball
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0,Basketball
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0,Basketball
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0,Basketball
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0,Basketball
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0,Basketball
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0,Basketball
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0,Basketball
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0,Basketball
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0,Basketball
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0,Basketball
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0,Basketball
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0,Basketball
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0,Basketball
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0,Basketball
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0,Basketball
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0,Basketball
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0,Basketball
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0,Basketball
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0,Basketball
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0,Basketball
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0,Basketball
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0,Basketball
...,...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0,Basketball
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0,Basketball
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0,Basketball
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0,Basketball
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0,Basketball
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0,Basketball
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0,Basketball
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0,Basketball
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0,Basketball
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0,Basketball
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0,Basketball
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0,Basketball
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0,Basketball
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0,Basketball
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0,Basketball
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0,Basketball
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0,Basketball
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0,Basketball
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0,Basketball
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0,Basketball
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0,Basketball
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0,Basketball
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0,Basketball
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0,Basketball
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,Basketball
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball

In [38]:
nba["League"] = "National Basketball Association"
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,League
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,National Basketball Association
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,National Basketball Association
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,National Basketball Association

In [39]:
nba = pd.read_csv("nba.csv")

In [40]:
nba.insert(3,column = "Sport", value = "Basketball") #adding a column at position 3 and everything else is pushed to the right

In [41]:
nba.insert(7, column = "League", value = "National Basketball Association")

## Broadcasting Operations

In [42]:
nba = pd.read_csv("nba.csv") #reloads the original dataframe

In [43]:
nba["Age"].add(5) #adds 5 to each value of age
                  #works also for NaN values
nba["Age"] + 5    #works exactly like the previous one

nba["Salary"].sub(10000) #substract 10000 from every salary value
nba["Salary"] - 10000    #works exactly like the previuos command

nba["Weight"].mul(0.453592)  #returns weight in kilograms
nba["Weight"] * 0.453592     #works exactly like the previuos command

nba["Weight in kilograms"] = nba["Weight"] * 0.453592 #creates a new column 
nba["Salary"].div(1000000)
nba["Salary in Millions"] = nba["Salary"] / 1000000 #creates a new column with salary in million

In [44]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Weight in kilograms,Salary in Millions
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,81.64656,7.730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,106.59412,6.796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,92.98636,NaN

## A Review of the .value_counts() Method

In [45]:
nba = pd.read_csv("nba.csv") #reloads the original dataframe

In [46]:
nba["Team"].value_counts()
nba["Position"].value_counts()

SG    102
PF    100
PG     92
SF     85
C      78
Name: Position, dtype: int64

In [47]:
nba["Salary"].value_counts() #most popular salary

947276.0      31
845059.0      18
525093.0      13
981348.0       6
1100602.0      5
16407500.0     5
5000000.0      5
12000000.0     5
8000000.0      5
4000000.0      5
3000000.0      4
7000000.0      4
2814000.0      4
1000000.0      4
19689000.0     4
200600.0       3
8500000.0      3
2500000.0      3
1015421.0      3
2854940.0      3
13500000.0     3
5543725.0      3
2288205.0      2
1270964.0      2
2900000.0      2
1007026.0      2
111444.0       2
13000000.0     2
1500000.0      2
1842000.0      2
              ..
2239800.0      1
1474440.0      1
19688000.0     1
7900000.0      1
2008748.0      1
13800000.0     1
2841960.0      1
1404600.0      1
1584480.0      1
273038.0       1
9213483.0      1
3272091.0      1
3075880.0      1
2250000.0      1
4626960.0      1
1304520.0      1
12100000.0     1
7500000.0      1
295327.0       1
2836186.0      1
6486486.0      1
5016000.0      1
3333333.0      1
1824360.0      1
8042895.0      1
1242720.0      1
2489530.0      1
5103120.0      1
9463484.0      1
700902.0       1
Name: Salary, Length: 309, dtype: int64

## Drop Rows with Null Values

In [48]:
nba = pd.read_csv("nba.csv") #reloads the original dataframe

In [99]:
nba.dropna()  #removes any rows from the dataframe if there is one or more NaN value
              #if there is a row with any value of NaN it will be removed

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0
...,...,...,...,...,...,...,...,...,...
422,Cameron Payne,Oklahoma City Thunder,22.0,PG,21.0,6-3,185.0,Murray State,2021520.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
424,Kyle Singler,Oklahoma City Thunder,5.0,SF,28.0,6-8,228.0,Duke,4500000.0
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,24.0,6-4,220.0,Syracuse,5138430.0
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [107]:
nba.dropna(how = "all") #drops rows if all values in a row are NaN

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [109]:
nba.dropna(axis = 1) ####!!!!THIS SHOULD NOT REMOVE ALL THE COLUMNS BUT JUST THOSE WITH any NaN

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
nba.dropna(subset = ["Salary", "College"]) #Removes rows where the salary and College valuea are NaN

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0
...,...,...,...,...,...,...,...,...,...
422,Cameron Payne,Oklahoma City Thunder,22.0,PG,21.0,6-3,185.0,Murray State,2021520.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
424,Kyle Singler,Oklahoma City Thunder,5.0,SF,28.0,6-8,228.0,Duke,4500000.0
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,24.0,6-4,220.0,Syracuse,5138430.0
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

## Fill in Null values with the .fillna() Method

In [112]:
nba.fillna(0) #filling every NaN is not a good idea for different data types in a dataframe
              #it is better to use fillna on a Series

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,0,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,0,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,0,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,0,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,0,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,0,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,0,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,0,0,0.0,0,0.0,0,0.0,0,0.0

In [114]:
nba["Salary"].fillna(0) #call fillna ona series for salary

0       7730337.0
1       6796117.0
2             0.0
3       1148640.0
4       5000000.0
5      12000000.0
6       1170960.0
7       2165160.0
8       1824360.0
9       3431040.0
10      2569260.0
11      6912869.0
12      3425510.0
13      1749840.0
14      2616975.0
15      3425510.0
16       845059.0
17      1500000.0
18      1335480.0
19      6300000.0
20      1599840.0
21       134215.0
22      1500000.0
23     19689000.0
24      1140240.0
25       947276.0
26       981348.0
27       947276.0
28       947276.0
29     11235955.0
          ...
428     8042895.0
429      625093.0
430      947276.0
431     6980802.0
432     2894059.0
433     6000000.0
434     5016000.0
435     3075880.0
436     4236287.0
437     2525160.0
438      525093.0
439     1415520.0
440     2854940.0
441     2637720.0
442     4775000.0
443     2658240.0
444     9463484.0
445     3777720.0
446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           0.0
Name: Salary, Length: 458, dtype: float64

In [116]:
nba["College"].fillna("No college")  #replace the NaN in college column with a string

0                  Texas
1              Marquette
2      Boston University
3          Georgia State
4             No college
5             No college
6                    LSU
7                Gonzaga
8             Louisville
9         Oklahoma State
10            Ohio State
11            Washington
12            Ohio State
13              Kentucky
14        North Carolina
15            No college
16        Oklahoma State
17        North Carolina
18               Arizona
19          Georgia Tech
20            No college
21            Cincinnati
22            Miami (FL)
23              Stanford
24              Syracuse
25           Saint Louis
26                Kansas
27            Georgetown
28             Texas A&M
29          Georgia Tech
             ...
428          Wake Forest
429           Notre Dame
430           California
431       North Carolina
432           St. John's
433                 Duke
434     Central Michigan
435             Illinois
436          Weber State
437               Lehigh
438       Westchester CC
439                 Duke
440               Dayton
441              Indiana
442              Clemson
443             Michigan
444             Colorado
445           No college
446         Georgia Tech
447           No college
448               Butler
449                 Duke
450           No college
451               Dayton
452             Kentucky
453               Butler
454           No college
455           No college
456               Kansas
457           No college
Name: College, Length: 458, dtype: object

## The .astype() Method

In [49]:
nba.tail(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
nba.dropna(how="all", inplace = True)

In [51]:
nba["Salary"].fillna(0, inplace = True)

In [52]:
nba["College"].fillna("None", inplace = True)

In [53]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [54]:
nba.info()  #we can see all of these series have the exact same number of values in the column

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null float64
dtypes: float64(4), object(5)
memory usage: 35.7+ KB

In [55]:
nba["Salary"] = nba["Salary"].astype("int")  #convert Salary series to integers
                                             #does not have the inplace=True parameter
                                             #we need to reassign it to the series

In [56]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0

In [57]:
nba["Number"] = nba["Number"].astype("int")

In [58]:
nba["Position"].nunique()

5

In [59]:
nba["Position"] = nba["Position"].astype("category") #assign Position a category type

In [60]:
nba["Team"].nunique()

30

In [61]:
nba["Team"] = nba["Team"].astype("category") #assign Team a category type

In [62]:
nba.info() #using type category for descrete values can lower the memory usage of the dataframe

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null category
Number      457 non-null int32
Position    457 non-null category
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null int32
dtypes: category(2), float64(2), int32(2), object(3)
memory usage: 27.6+ KB

## Sort a DataFrame with the .sort_value() method, Part 1

In [63]:
nba.sort_values("Name", ascending = False, inplace=True,na_position="last" )  #stores the entire dataframe by values in name series 
                                                        #descending order
                                                        #inplace
                                                        #NaN values will be placed at the end due to the na_position parameter

## Sort a DataFrame with the .sort_value() method, Multiple columns

nba = pd.read_csv("nba.csv")

In [64]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
237,Zaza Pachulia,Dallas Mavericks,27,C,32.0,6-11,275.0,None,5200000
271,Zach Randolph,Memphis Grizzlies,50,PF,34.0,6-9,260.0,Michigan State,9638555
402,Zach LaVine,Minnesota Timberwolves,8,PG,21.0,6-5,189.0,UCLA,2148360

In [65]:
nba.sort_values(["Team", "Name"], ascending = False)   #first sort by team and then sort by name
                                                       #in descending order

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
379,Ramon Sessions,Washington Wizards,7,PG,30.0,6-3,190.0,Nevada,2170465
378,Otto Porter Jr.,Washington Wizards,22,SF,23.0,6-8,198.0,Georgetown,4662960
375,Nene Hilario,Washington Wizards,42,C,33.0,6-11,250.0,None,13000000
376,Markieff Morris,Washington Wizards,5,PF,26.0,6-10,245.0,Kansas,8000000
381,Marcus Thornton,Washington Wizards,15,SF,29.0,6-4,205.0,LSU,200600
373,Marcin Gortat,Washington Wizards,13,C,32.0,6-11,240.0,None,11217391
377,Kelly Oubre Jr.,Washington Wizards,12,SF,20.0,6-7,205.0,Kansas,1920240
382,John Wall,Washington Wizards,2,PG,25.0,6-4,195.0,Kentucky,15851950
371,Jarell Eddie,Washington Wizards,8,SG,24.0,6-7,218.0,Virginia Tech,561716
370,Jared Dudley,Washington Wizards,1,SF,30.0,6-7,225.0,Boston College,4375000
374,JJ Hickson,Washington Wizards,21,C,27.0,6-9,242.0,North Carolina State,273038
380,Garrett Temple,Washington Wizards,17,SG,30.0,6-6,195.0,LSU,1100602
372,Drew Gooden,Washington Wizards,90,PF,34.0,6-10,250.0,Kansas,3300000
369,Bradley Beal,Washington Wizards,3,SG,22.0,6-5,207.0,Florida,5694674
368,Alan Anderson,Washington Wizards,6,SG,33.0,6-6,220.0,Michigan State,4000000
452,Trey Lyles,Utah Jazz,41,PF,20.0,6-10,234.0,Kentucky,2239800
443,Trey Burke,Utah Jazz,3,PG,23.0,6-1,191.0,Michigan,2658240
442,Trevor Booker,Utah Jazz,33,PF,28.0,6-8,228.0,Clemson,4775000
455,Tibor Pleiss,Utah Jazz,21,C,26.0,7-3,256.0,None,2900000
453,Shelvin Mack,Utah Jazz,8,PG,26.0,6-3,203.0,Butler,2433333
447,Rudy Gobert,Utah Jazz,27,C,23.0,7-1,245.0,None,1175880
449,Rodney Hood,Utah Jazz,5,SG,23.0,6-8,206.0,Duke,1348440
454,Raul Neto,Utah Jazz,25,PG,24.0,6-1,179.0,None,900000
450,Joe Ingles,Utah Jazz,2,SF,28.0,6-8,226.0,None,2050000
456,Jeff Withey,Utah Jazz,24,C,26.0,7-0,231.0,Kansas,947276
448,Gordon Hayward,Utah Jazz,20,SF,26.0,6-8,226.0,Butler,15409570
446,Derrick Favors,Utah Jazz,15,PF,24.0,6-10,265.0,Georgia Tech,12000000
445,Dante Exum,Utah Jazz,11,PG,20.0,6-6,190.0,None,3777720
451,Chris Johnson,Utah Jazz,23,SF,26.0,6-6,206.0,Dayton,981348
444,Alec Burks,Utah Jazz,10,SG,24.0,6-6,214.0,Colorado,9463484
...,...,...,...,...,...,...,...,...,...
14,Tyler Zeller,Boston Celtics,44,C,26.0,7-0,253.0,North Carolina,2616975
8,Terry Rozier,Boston Celtics,12,PG,22.0,6-2,190.0,Louisville,1824360
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
9,Marcus Smart,Boston Celtics,36,PG,22.0,6-4,220.0,Oklahoma State,3431040
7,Kelly Olynyk,Boston Celtics,41,C,25.0,7-0,238.0,Gonzaga,2165160
6,Jordan Mickey,Boston Celtics,55,PF,21.0,6-8,235.0,LSU,1170960
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,None,5000000
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
10,Jared Sullinger,Boston Celtics,7,C,24.0,6-9,260.0,Ohio State,2569260
13,James Young,Boston Celtics,13,SG,20.0,6-6,215.0,Kentucky,1749840
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
11,Isaiah Thomas,Boston Celtics,4,PG,27.0,5-9,185.0,Washington,6912869
12,Evan Turner,Boston Celtics,11,SG,27.0,6-7,220.0,Ohio State,3425510
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
5,Amir Johnson,Boston Celtics,90,PF,29.0,6-9,240.0,None,12000000
322,Walter Tavares,Atlanta Hawks,22,C,24.0,7-3,260.0,None,1000000
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24.0,6-6,205.0,Michigan,1304520
321,Tiago Splitter,Atlanta Hawks,11,C,31.0,6-11,245.0,None,9756250
320,Thabo Sefolosha,Atlanta Hawks,25,SF,32.0,6-7,220.0,None,4000000
315,Paul Millsap,Atlanta Hawks,4,PF,31.0,6-8,246.0,Louisiana Tech,18671659
319,Mike Scott,Atlanta Hawks,32,PF,27.0,6-8,237.0,Virginia,3333333
316,Mike Muscala,Atlanta Hawks,31,PF,24.0,6-11,240.0,Bucknell,947276
317,Lamar Patterson,Atlanta Hawks,13,SG,24.0,6-5,225.0,Pittsburgh,525093
314,Kyle Korver,Atlanta Hawks,26,SG,35.0,6-7,212.0,Creighton,5746479
313,Kris Humphries,Atlanta Hawks,43,PF,31.0,6-9,235.0,Minnesota,1000000
311,Kirk Hinrich,Atlanta Hawks,12,SG,35.0,6-4,190.0,Kansas,2854940
309,Kent Bazemore,Atlanta Hawks,24,SF,26.0,6-5,201.0,Old Dominion,2000000
323,Jeff Teague,Atlanta Hawks,0,PG,27.0,6-2,186.0,Wake Forest,8000000
318,Dennis Schroder,Atlanta Hawks,17,PG,22.0,6-1,172.0,None,1763400
312,Al Horford,Atlanta Hawks,15,C,30.0,6-10,245.0,Florida,12000000

In [66]:
nba.sort_values(["Team", "Name"], ascending = [True, False])  #team is sorted in alphabetical order
                                                              #name is sorted in descending order

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
322,Walter Tavares,Atlanta Hawks,22,C,24.0,7-3,260.0,None,1000000
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24.0,6-6,205.0,Michigan,1304520
321,Tiago Splitter,Atlanta Hawks,11,C,31.0,6-11,245.0,None,9756250
320,Thabo Sefolosha,Atlanta Hawks,25,SF,32.0,6-7,220.0,None,4000000
315,Paul Millsap,Atlanta Hawks,4,PF,31.0,6-8,246.0,Louisiana Tech,18671659
319,Mike Scott,Atlanta Hawks,32,PF,27.0,6-8,237.0,Virginia,3333333
316,Mike Muscala,Atlanta Hawks,31,PF,24.0,6-11,240.0,Bucknell,947276
317,Lamar Patterson,Atlanta Hawks,13,SG,24.0,6-5,225.0,Pittsburgh,525093
314,Kyle Korver,Atlanta Hawks,26,SG,35.0,6-7,212.0,Creighton,5746479
313,Kris Humphries,Atlanta Hawks,43,PF,31.0,6-9,235.0,Minnesota,1000000
311,Kirk Hinrich,Atlanta Hawks,12,SG,35.0,6-4,190.0,Kansas,2854940
309,Kent Bazemore,Atlanta Hawks,24,SF,26.0,6-5,201.0,Old Dominion,2000000
323,Jeff Teague,Atlanta Hawks,0,PG,27.0,6-2,186.0,Wake Forest,8000000
318,Dennis Schroder,Atlanta Hawks,17,PG,22.0,6-1,172.0,None,1763400
312,Al Horford,Atlanta Hawks,15,C,30.0,6-10,245.0,Florida,12000000
14,Tyler Zeller,Boston Celtics,44,C,26.0,7-0,253.0,North Carolina,2616975
8,Terry Rozier,Boston Celtics,12,PG,22.0,6-2,190.0,Louisville,1824360
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
9,Marcus Smart,Boston Celtics,36,PG,22.0,6-4,220.0,Oklahoma State,3431040
7,Kelly Olynyk,Boston Celtics,41,C,25.0,7-0,238.0,Gonzaga,2165160
6,Jordan Mickey,Boston Celtics,55,PF,21.0,6-8,235.0,LSU,1170960
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,None,5000000
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
10,Jared Sullinger,Boston Celtics,7,C,24.0,6-9,260.0,Ohio State,2569260
13,James Young,Boston Celtics,13,SG,20.0,6-6,215.0,Kentucky,1749840
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
11,Isaiah Thomas,Boston Celtics,4,PG,27.0,5-9,185.0,Washington,6912869
12,Evan Turner,Boston Celtics,11,SG,27.0,6-7,220.0,Ohio State,3425510
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
5,Amir Johnson,Boston Celtics,90,PF,29.0,6-9,240.0,None,12000000
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20.0,6-10,234.0,Kentucky,2239800
443,Trey Burke,Utah Jazz,3,PG,23.0,6-1,191.0,Michigan,2658240
442,Trevor Booker,Utah Jazz,33,PF,28.0,6-8,228.0,Clemson,4775000
455,Tibor Pleiss,Utah Jazz,21,C,26.0,7-3,256.0,None,2900000
453,Shelvin Mack,Utah Jazz,8,PG,26.0,6-3,203.0,Butler,2433333
447,Rudy Gobert,Utah Jazz,27,C,23.0,7-1,245.0,None,1175880
449,Rodney Hood,Utah Jazz,5,SG,23.0,6-8,206.0,Duke,1348440
454,Raul Neto,Utah Jazz,25,PG,24.0,6-1,179.0,None,900000
450,Joe Ingles,Utah Jazz,2,SF,28.0,6-8,226.0,None,2050000
456,Jeff Withey,Utah Jazz,24,C,26.0,7-0,231.0,Kansas,947276
448,Gordon Hayward,Utah Jazz,20,SF,26.0,6-8,226.0,Butler,15409570
446,Derrick Favors,Utah Jazz,15,PF,24.0,6-10,265.0,Georgia Tech,12000000
445,Dante Exum,Utah Jazz,11,PG,20.0,6-6,190.0,None,3777720
451,Chris Johnson,Utah Jazz,23,SF,26.0,6-6,206.0,Dayton,981348
444,Alec Burks,Utah Jazz,10,SG,24.0,6-6,214.0,Colorado,9463484
379,Ramon Sessions,Washington Wizards,7,PG,30.0,6-3,190.0,Nevada,2170465
378,Otto Porter Jr.,Washington Wizards,22,SF,23.0,6-8,198.0,Georgetown,4662960
375,Nene Hilario,Washington Wizards,42,C,33.0,6-11,250.0,None,13000000
376,Markieff Morris,Washington Wizards,5,PF,26.0,6-10,245.0,Kansas,8000000
381,Marcus Thornton,Washington Wizards,15,SF,29.0,6-4,205.0,LSU,200600
373,Marcin Gortat,Washington Wizards,13,C,32.0,6-11,240.0,None,11217391
377,Kelly Oubre Jr.,Washington Wizards,12,SF,20.0,6-7,205.0,Kansas,1920240
382,John Wall,Washington Wizards,2,PG,25.0,6-4,195.0,Kentucky,15851950
371,Jarell Eddie,Washington Wizards,8,SG,24.0,6-7,218.0,Virginia Tech,561716
370,Jared Dudley,Washington Wizards,1,SF,30.0,6-7,225.0,Boston College,4375000
374,JJ Hickson,Washington Wizards,21,C,27.0,6-9,242.0,North Carolina State,273038
380,Garrett Temple,Washington Wizards,17,SG,30.0,6-6,195.0,LSU,1100602
372,Drew Gooden,Washington Wizards,90,PF,34.0,6-10,250.0,Kansas,3300000
369,Bradley Beal,Washington Wizards,3,SG,22.0,6-5,207.0,Florida,5694674
368,Alan Anderson,Washington Wizards,6,SG,33.0,6-6,220.0,Michigan State,4000000

## Sort DataFrame with .sort_index() Method

In [67]:
nba.sort_values(["Number", "Salary", "Name"], inplace = True)

In [68]:
nba.tail(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
5,Amir Johnson,Boston Celtics,90,PF,29.0,6-9,240.0,None,12000000
68,Lucas Nogueira,Toronto Raptors,92,C,23.0,7-0,220.0,None,1842000
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117

In [71]:
nba.sort_index(inplace=True) #index sorted  in ascending order and make it permanent

## Rank Values with the .rank() Method

In [78]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba["Salary"] = nba["Salary"].fillna(0).astype("int")

In [79]:
nba.head(4)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640

In [84]:
nba["Salary rank"] = nba["Salary"].rank(ascending=False).astype("int")
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary rank
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337,97
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117,110
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452

In [ ]:
nba.sort_values()